"""Serialize/deserialize a Project to a ``.dmosh`` JSON project file.

A project stores clip *sources* and their per-clip mosh settings plus the timeline
arrangement — never the normalized/temp media (those are regenerated by re-ingesting
on load). Injected I-frame clips store their source media + format so they can be
rebuilt with the inject worker.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

PROJECT_FORMAT = "datamosh-project"
PROJECT_VERSION = 1
PROJECT_SUFFIX = ".dmosh"


class ProjectLoadError(Exception):
    """Raised when a .dmosh file cannot be read or is not a valid project."""


def serialize(project, import_settings: dict[str, Any], app_version: str) -> dict[str, Any]:
    """Build a JSON-serializable dict describing the project's editable state."""
    clips = list(project.clips)
    index_of = {id(c): i for i, c in enumerate(clips)}

    clip_data: list[dict[str, Any]] = []
    for clip in clips:
        entry: dict[str, Any] = {
            "kind": clip.source_kind,
            "source_path": str(clip.source_path),
            "keep_first": clip.keep_first,
            "duplicate_count": clip.duplicate_count,
            "duplicate_gap": clip.duplicate_gap,
            "drop_first_keyframe": clip.drop_first_keyframe,
            "keep_keys_spec": clip.keep_keys_spec,
            "drop_keys_spec": clip.drop_keys_spec,
        }
        if clip.source_kind == "iframe":
            entry["iframe_fps"] = clip.fps
            entry["iframe_width"] = clip.frame_width or None
            entry["iframe_height"] = clip.frame_height or None
        clip_data.append(entry)

    timeline_data: list[dict[str, Any]] = []
    for item in project.timeline_items:
        clip_index = index_of.get(id(item.clip))
        if clip_index is None:
            continue
        timeline_data.append({
            "clip_index": clip_index,
            "in_frame": item.in_frame,
            "out_frame": item.out_frame,
            "drop_first_keyframe_override": item.drop_first_keyframe_override,
            "keep_first_override": item.keep_first_override,
            "duplicate_count_override": item.duplicate_count_override,
            "duplicate_gap_override": item.duplicate_gap_override,
            "keep_keys_spec_override": item.keep_keys_spec_override,
            "drop_keys_spec_override": item.drop_keys_spec_override,
        })

    return {
        "format": PROJECT_FORMAT,
        "version": PROJECT_VERSION,
        "app_version": app_version,
        "import_settings": dict(import_settings or {}),
        "clips": clip_data,
        "timeline": timeline_data,
        "selected_row": project.selected_row,
        "selected_timeline_index": project.selected_timeline_index,
    }


def write_project(path: Path, project, import_settings: dict[str, Any], app_version: str) -> None:
    """Serialize ``project`` and write it to ``path`` as pretty JSON."""
    data = serialize(project, import_settings, app_version)
    Path(path).write_text(json.dumps(data, indent=2), encoding="utf-8")


def read_project(path: Path) -> dict[str, Any]:
    """Read and validate a .dmosh file, returning its parsed dict."""
    try:
        raw = Path(path).read_text(encoding="utf-8")
    except OSError as exc:
        raise ProjectLoadError(f"Could not open project file:\n{exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ProjectLoadError(f"Project file is not valid JSON:\n{exc}") from exc

    if not isinstance(data, dict) or data.get("format") != PROJECT_FORMAT:
        raise ProjectLoadError("This file is not a Datamosh project (.dmosh).")
    try:
        file_version = int(data.get("version", 0))
    except (TypeError, ValueError):
        file_version = 0
    if file_version > PROJECT_VERSION:
        raise ProjectLoadError(
            "This project was saved by a newer version of Datamosh. Update the app to open it."
        )
    if not isinstance(data.get("clips"), list) or not isinstance(data.get("timeline"), list):
        raise ProjectLoadError("Project file is missing its clips/timeline data.")
    return data
